# Generated by Django 5.1 on 2025-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_healthlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
