# Generated by Django 5.2 on 2025-04-26 01:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_healthlog_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteexercise',
            options={},
        ),
        migrations.AddField(
            model_name='healthlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='favoriteexercise',
            name='body_part',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='favoriteexercise',
            name='equipment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='favoriteexercise',
            name='gif_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='favoriteexercise',
            name='target',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='favoriteexercise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='cardio_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='DailyHealthLog',
        ),
    ]
