# Generated by Django 5.2 on 2025-04-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_favoriteexercise_options_healthlog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='FavoriteExercise',
        ),
    ]
