# Generated by Django 5.2 on 2025-04-26 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_healthlog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.workout'),
        ),
    ]
